# Application makefile

# Command name (Public function 'int <APPNAME>_main(void)' required)
APPNAME = mavlink_control

# Application execute priority (Range: 0 ~ 255, Default: 100)
PRIORITY =

# Application stack memory size (Default: 2048)
STACKSIZE =

CXXEXT = .cpp

# Main source code
MAINSRC = mavlink_control.cpp

# Additional C source files (*.c)
CSRCS =

# Additional C++ source files (*.cxx)
CXXSRCS = 

# Additional assembler source files (*.S)
ASRCS =

# C compiler flags
CFLAGS =

# C++ compiler flags
CXXFLAGS = -fexceptions -I mavlink/include/mavlink/v2.0

include $(SPRESENSE_HOME)/.vscode/application.mk
